name: Student Management CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Show project files
        run: ls -la

      - name: Compile Java files
        run: |
          mkdir -p out
          find . -name "*.java" -not -path "./out/*" -print0 | xargs -0 javac -d out

      - name: Package application
        run: |
          jar cf student-management.jar -C out .

      - name: Upload application package
        uses: actions/upload-artifact@v4
        with:
          name: student-management-package
          path: student-management.jar
          